---
title: "Tempature Forecasting via Time Series Analysis"
author: "Xinyu Zhang"
date: "2022/2/20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# time series forecasting
# library(rworldmap) #???? may not be used
library(TSA) # eacf
library("tseries") # adf.test
library(forecast) #auto.arima
library(dplyr)
library(fpp3) # time series models
library(feasts)
library(ggplot2)
library(fable)
```

 

```{r loadData}
cherry <- read.csv("../data/FinalizedData/FinalData/Liestal.csv")

str(cherry)
first_date = as.Date(cherry$DATE[1])
target_date = as.Date("1999-12-31")
train_range = seq(first_date, target_date, by="days")

precip = cherry$PRCP[1:length(train_range)]
temp = cherry$TAVG[1:length(train_range)]
date = (as.Date(as.character(cherry$DATE)))[1:length(train_range)]
year = cherry$year[1:length(train_range)]
data = data.frame(precip, temp, date, year)
str(data)
head(data,2)
tail(data,2)
data_year = data %>% filter(year==1999)

```

```{r plot, fig.width=8, fig.height=3, warning=FALSE, message=FALSE}
par(mfrow=c(1,2))
#### Step 1: Preview
# Use ACF to identify the type of time series
acf(ts(data_year$temp), lag.max = 100, col = 'dark blue', bg = 'dark blue', 
    panel.first = grid(), main = 'ACF Plot of Adj. Price of AAPL', lwd=.01)
# Based on acf plot, we know that it is more likely to be an AR process
pacf(ts(data_year$temp), lag.max = 10, col = 'dark blue', bg = 'dark blue', 
     panel.first = grid(), main = 'PACF Plot of Adj. Price of AAPL')
# Since PACF damp out for AR(p) process when lag > p, we could guess that 
# it follows AR(p) process with p around 1 (or maybe 3? Or maybe ARMA)
adf.test(ts(data_year$temp))
# This means the trend has to be estimated

plot(x=data$date, y=ts(data$temp), main = "TS Plot of Temperature", type="l",
     col = 'dark blue', bg = 'dark blue',  panel.first = grid(), lty=1, ylab="Temperature", xlab="Day")

plot(x=data_year$date, y=ts(data_year$temp), main = "TS Plot of Temperature in 2020", type="l",
     col = 'dark blue', bg = 'dark blue',  panel.first = grid(), lty=1, ylab="Temperature", xlab="Day")

data_ts = as_tsibble(data, index=date)
data_ts %>%
  autoplot(temp, col="dark blue") +
  labs(x="Date", y = "Temperature", title = "Time series")

#'  Trend decomposition using additive model since the The additive 
#'  decomposition is the most appropriate if the magnitude of the 
#'  seasonal fluctuations, or the variation around the trend-cycle,
#'   does not vary with the level of the time series.

```



```{r}
#### Step 2 STL Decomposition
dcmp <- data_ts %>% 
  model(stl = STL(temp ~ trend(window=7), robust=TRUE)) %>%
  components() %>%
  select(-.model)
head(dcmp)

```

```{r}
#### Step 3 Forecasting
target_date2 = as.Date("2021-12-31")
prediction_range = seq(target_date+1, target_date2, by="days")
h = length(prediction_range)
fcst = dcmp %>%
  model(SNAIVE(temp~lag("year"))) %>%
  forecast(h=h)

fcst %>% autoplot(dcmp) +
  labs(y = "Temperature",
       title = "TS Forecast of Temperature")

temperature_fcst = fcst$.mean
date.f = seq(from=tail(data$date,1)+1, to=tail(data$date,1)+h, length.out=h)


cumsum = temperature_fcst[1]
CDD_vector = temperature_fcst;
for (i in 2:length(date.f)) {
  if (as.integer(format(date.f[i],"%Y")) > as.integer(format(date.f[i-1],"%Y"))) {
    cumsum = 0
  }
  CDD_vector[i] = cumsum + temperature_fcst[i]
  cumsum = CDD_vector[i]
}

data.forecast = data.frame(temp=temperature_fcst, date=date.f,CDD = CDD_vector)
#data_total = rbind(data[,c('temp','date')],data.forecast)
str(data.forecast)


write.csv(data.forecast,"../data/FinalizedData/FinalData/Liestal_temp_forecast_2000_2021.csv")

summary(data.forecast)

```

